---
- name: generate Nginx site config
  template:
     src: site.conf.j2
     dest: /etc/nginx/sites-available/site.cfg
     owner: root
     group: root
     mode: 0755
- name: create symlink
  file:
    src: /etc/nginx/sites-available/site.cfg
    dest: /etc/nginx/sites-enabled/default
    state: link
- name: restart nginx
  service:
    name: nginx
    state: restarted
